server:
  port: 8080

spring:
  spring:
    profiles:
      active: local # local profile 사용하기 위한 설정

  h2:     # h2 db 임베디드 버전
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/flyway;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false # 기본값 = true 이지만, flyway를 사용하고 있음을 명시해줍니다.
    # local 에서만 true로 되도록 설정한다.
    baseline-on-migrate: true  # 베이스라인 설정 값이 필요한 상황에서 마이그레이션 설정 값
